travis:
  secure:
    BINSTAR_TOKEN: U2F2PxLcGs+yoUknjcqrayvtwBEcNQqzH5bQF9hxj1ZdKlRVn+WVion1rvulvfGZ3QfEwu4o989TEORlmT4FQQjbQ0V0vM1PW6/XvQBL0sF3SkwCaQhwRXoddAf8HdN5/Fm2sK/Ndg6s0LjtVze9zMQxcMzVJrAsS3BMZxTt0ik9/J8ch8+FjcCYyqBSaJ04JO9UwzLmEf7XB4GOE5/AxsbZ4tbziEKbJDJxJNi1b7ePSri4putBhsdlAcumoWazR1JNT/L8lI3kCElC0/9kKjTWkhCj0eydYgyoWjQpy7SVAgVlDbmmr7A0EDx48BPEnRmH9gR/FTG/Ie5CKhnnDdffYckiUuWMOgobXRPl+5SV7Avz7LjhqWN5BS2Si9imsxy91ZFMfhA3RdWzisiAs7C8qZ9YCYvOlOUcOBa8dOTY1AGyWSty7g1VekeCWV8x2agxCw2Eamc4S/vhbcjFAUmoOf7NNUAEU8ATG5vobgQ0Hg8/r8LxRXZukTWzjcuoRnDaV9yne9vK+qeniFrRVQpgLcNyzUgVdyeMsO+2Sbh5A6f1go0T0z3zJfbc5yf2h1UbgJH9C3sUqg4R2Y46+vnp7suNkep1FOr/z/LAvwqONepKKz6AopJg+A0eVeYH8KJJXUUME6iy8lOty3yZD9LSppx72lnl73Mtfh4SNF0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
